name: flutter_web_plugins
description: Library to register Flutter Web plugins
author: Flutter Authors <flutter-dev@googlegroups.com>
homepage: http://flutter.dev
environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
dependencies:
  flutter:
    git:
      url: https://github.com/mpflutter/mpflutter
      path: packages/flutter
  characters: 1.1.0
  collection: 1.15.0
  meta: 1.3.0
  typed_data: 1.3.0
  vector_math: 2.1.0
dev_dependencies:
  async: 2.5.0
  boolean_selector: 2.1.0
  charcode: 1.2.0
  clock: 1.1.0
  file: 6.0.0
  matcher: 0.12.10
  path: 1.8.0
  platform: 3.0.0
  process: 4.0.0
  source_span: 1.8.0
  stack_trace: 1.10.0
  stream_channel: 2.1.0
  string_scanner: 1.1.0
  term_glyph: 1.2.0
  test_api: 0.2.19
dependency_overrides:
  flutter:
    path: ../flutter
version: 0.18.1
